name: PR Agent for NULP

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run PR Agent on every pull request
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: pr-agent-nulp
        uses: shakhanton/Pr-Agent-NULP@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_CREDENTIALS_CONTENT: ${{ secrets.GOOGLE_CREDENTIALS_CONTENT }}
          GOOGLE_SPREADSHEET_URL: ${{ secrets.GOOGLE_SPREADSHEET_URL }}
          LAB_PATH_RULES: >-
            {
              "lab-1": ["domain1/terraform/main.tf", "domain1/terraform/lambda.tf", "domain1/terraform/api.tf", "domain1/terraform/iam.tf", "domain1/lambdas/"],
              "lab-2": ["domain1/terraform/frontend.tf", "domain1/terraform/cloudwatch.tf", "domain1/terraform/notifications.tf"],
              "lab-3": ["domain2/k8s/postgres/", "domain2/k8s/backend/", "domain2/k8s/secret.yaml"],
              "lab-4": ["domain2/k8s/frontend/", "domain2/k8s/ingress.yaml"]
            }
          MAX_ATTEMPTS: "3"
